FROM nvcr.io/nvidia/l4t-ml:r36.2.0-py3

ENV PYTHONUNBUFFERED=1

# ============================================
# TensorFlow GPU Configuration
# ============================================
ENV TF_FORCE_GPU_ALLOW_GROWTH=true
ENV TF_GPU_ALLOCATOR=default
ENV TF_NUM_INTRAOP_THREADS=1
ENV TF_NUM_INTEROP_THREADS=1
ENV OMP_NUM_THREADS=1
ENV OPENBLAS_NUM_THREADS=1
ENV TF_CPP_MIN_LOG_LEVEL=2

WORKDIR /app

COPY FL_client/src/ /app/src

WORKDIR /app/src

RUN pip3 install --no-cache-dir --upgrade pip

RUN pip3 install --no-cache-dir -r requirements.txt

WORKDIR /app/src

CMD ["python3", "client.py"]